version: '3'

services:
  app:
    build:
      context: .
    container_name: app
    tty: true  
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"    
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=devfull
      - MYSQL_ROOT_PASSWORD=senha
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
