version: '3'

services:
  app:
    build:
      context: node
    container_name: node_app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node app.js docker-entrypoint.sh
    tty: true  
    volumes:
      # - ./node:/usr/src/app
      - /usr/src/app/node_modules
    # ports:
    #   - "3000:3000"    
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network    

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=devfull
      - MYSQL_ROOT_PASSWORD=senha
    ports:
      - "3306:3306"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
